### ISSUE TITLE
When will the ranker code be released?

### ISSUE THREAD

**Issue by chijames** [moutaigua8183/BookQA#2]
As title.

**Comment by moutaigua8183** [comment]
Hi James, 

Part of the ranker codes are released now. The rest of the ranker codes may need more time to clean up and will not be availble shortly, since the original developer is not available at this point.

Thanks!

**Comment by chijames** [comment]
May I know which part(s) is not released yet? Thanks.

**Comment by moutaigua8183** [comment]
In the context of our paper, they are HardEM and ICT rankers.
